version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi.py
    volumes:
      - ./auth/data:/app/data
    depends_on:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - auth
